const {
  REACT_APP_COUCHDB_URL,
  REACT_APP_COUCHDB_USERNAME,
  REACT_APP_COUCHDB_PASSWORD,
  REACT_APP_COUCHDB_DB_NAME,
} = process.env

export const COUCHDB_URL = REACT_APP_COUCHDB_URL
export const COUCHDB_USERNAME = REACT_APP_COUCHDB_USERNAME
export const COUCHDB_PASSWORD = REACT_APP_COUCHDB_PASSWORD
export const COUCHDB_DB_NAME = REACT_APP_COUCHDB_DB_NAME
